### PR TITLE
Use minimal babel presets for wyw to fix the website Cloudflare build

### PR DESCRIPTION
**Pull request by bosiraphael**
The website's Cloudflare build (`opennextjs-cloudflare` / Turbopack) was failing with `_defineProperty is not a function` while linaria/wyw evaluates `twenty-ui/dist/theme.cjs` at build time. It regressed in #21946, whose twenty-ui build rework changed the emitted `theme.cjs` so the theme objects ship as runtime object spreads (`{ ...THEME_COMMON }`).

**Cause:** wyw evaluates modules in Node through `next/babel`, which pulls in `preset-env` + `transform-runtime`. Those re-lower the runtime spreads into `@babel/runtime` helpers imported as ESM; wyw then `require()`s that ESM module in a CJS context where the export is not callable, so `_defineProperty` fails.

**Fix:** wyw runs in Node and needs no downleveling, so replace `next/babel` with minimal presets (`@babel/preset-typescript`, `@babel/preset-react`, `@wyw-in-js/babel-preset`, plus `@babel/plugin-transform-export-namespace-from`), matching twenty-front's wyw config. No `@babel/runtime` helpers get injected. Kept on the website side so twenty-ui keeps react/react-dom as peer deps (#21946).

Note: no blocking PR check runs the website production build, so this is best validated via the website preview build or the twenty-infra deploy.

### CODE REVIEW

**Review by FelixMalfait — APPROVED** [review]

**Comment by FelixMalfait** [comment]
Maybe try deploying it here before merging? https://github.com/twentyhq/twenty-infra/actions/workflows/deploy-website.yaml

**Comment by FelixMalfait** [comment]
Launched it: https://github.com/twentyhq/twenty-infra/actions/runs/28019081792

**Comment by mabdullahabaid** [comment]
Workflow run succeeded. Can we merge or are you still working on this? @bosiraphael
