### ISSUE TITLE
Front component build fails with Could not resolve "monaco-editor" when importing from twenty-ui/primitives/input

### ISSUE THREAD

**Issue by honzanemecek** [twentyhq/twenty#26117]
## Bug Description

A front component that imports a `Button` from `twenty-ui/primitives/input` does not build unless the app also installs `monaco-editor`:

```
$ yarn twenty dev:build
Building application files...
Build failed with 1 error:
node_modules/twenty-ui/dist/input-DOIOurw8.js:345:33: ERROR: Could not resolve "monaco-editor"
```

The component never renders `CodeEditor`. The failing import is `CodeEditor`'s lazy `import("monaco-editor")` from #23855. It sits in the chunk behind `twenty-ui/primitives/input`, and the `primitives/feedback` and `primitives/navigation` chunks import that chunk too. `monaco-editor` is a peer dependency. The twenty-ui README asks for it ("Install `monaco-editor` even if you never render a code editor", #26044), but the install step in [Using Twenty UI components](https://docs.twenty.com/developers/extend/apps/layout/front-components#using-twenty-ui-components) only adds `twenty-ui`, and the `create-twenty-app` template does not add it either.

**Repro.** Node 24.18, Yarn 4.13. A minimal app (application config and default role as in the `create-twenty-app` template) with `twenty-sdk`, `twenty-client-sdk` and `twenty-ui` at 2.41.0, `react` and `react-dom` 19, and no `monaco-editor`. Add:

```tsx
// src/front-components/button.tsx
import { defineFrontComponent } from 'twenty-sdk/define';
import { Button } from 'twenty-ui/primitives/input';

const ButtonOnly = () => <Button title="Hello" />;

export default defineFrontComponent({
  universalIdentifier: '0b7d3e61-5a2c-4f9e-8d14-7e6a1c3b2f45',
  name: 'Button only',
  component: ButtonOnly,
});
```

`yarn twenty dev:build` exits 1 with the error above.

It is the same on twenty-ui 1.0.0-alpha.2 (the version `create-twenty-app@2.40.0` pins) with twenty-sdk 2.31.0 and `import { Button } from 'twenty-ui/input'`: `dist/feedback-4pPehd1L.js:593:33: ERROR: Could not resolve "monaco-editor"`. 1.0.0-alpha.1 built, because its chunk only imported `@monaco-editor/react`.

## Expected behavior

A front component that uses a button, an input or a callout builds without installing a code editor it never renders. If `monaco-editor` has to stay a required peer, the front-component install step and the `create-twenty-app` template should include it.

## Technical inputs

- Only resolution needs the package. With `monaco-editor@0.56.0` installed (98 MB in `node_modules`) the component above builds to 754,865 bytes. With an empty package named `monaco-editor` (`export {}`) in its place, the output is byte-identical. The same holds on alpha.2 with twenty-sdk 2.31.0 (968,136 bytes both ways). The unused `CodeEditor` code is dropped, but its import still has to resolve.
- For that reason, marking the peer optional in `peerDependenciesMeta` would not fix the build on its own.
- Possible fix: give `CodeEditor` its own entry point (for example `twenty-ui/primitives/code-editor`), so the `input`, `feedback` and `navigation` chunks stop referencing `monaco-editor`.
- Workaround until then: a local workspace package named `monaco-editor` that only exports `{}`, pinned through `resolutions` in the root `package.json`.

**Comment by bosiraphael** [comment]
Hello @honzanemecek ! Sorry for the inconvenience. Thanks for the detailed reproduction.
Twenty-ui is still in alpha as stated on the docs. I'm currently migrating all primitives, and wanted to get rid of this dependency as well as react-router-dom at the end of the migration.
I'm working on a fix and will raise a PR soon. I'll keep you updated.
