### PR TITLE
Unwrap settings front components in the front component build

### PR DESCRIPTION
**Pull request by ehconitin**
## Summary

The front-component build transform only unwrapped `defineFrontComponent`, so a file using `defineSettingsFrontComponent` skipped the transform and built its ValidationResult object as the default export. The front-component renderer then crashed at load with "componentModule.default is not a function".

Broadens the unwrap patterns to cover both define functions and adds a spec case. Introduced in #23256 alongside the new define function; no app exercises the path yet.

## Validation

```
cd packages/twenty-sdk && npx vitest run --config vitest.unit.config.ts src/cli/utilities/build/common/front-component-build/utils/__tests__/unwrap-define-front-component-to-direct-export.spec.ts
```

<a href="https://cubic.dev/pr/twentyhq/twenty/pull/23631?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

File: packages/twenty-sdk/src/cli/utilities/build/common/front-component-build/utils/unwrap-define-front-component-to-direct-export.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 const DEFINE_FRONT_COMPONENT_IMPORT_PATTERN =
-  /import\s*\{\s*defineFrontComponent\s*\}\s*from\s*['"][^'"]+['"];?\n?/g;
+  /import\s*\{\s*define(?:Settings)?FrontComponent\s*\}\s*from\s*['"][^'"]+['"];?\n?/g;
```
[the remark this answers is not in the document]
Comment (ehconitin) [reply packages/twenty-sdk/src/cli/utilities/build/common/front-component-build/utils/unwrap-define-front-component-to-direct-export.ts:2]: The import matcher intentionally keeps the same shape it had for `defineFrontComponent` — sole-specifier only, now for both names. A surviving multi-specifier import isn't a runtime dependency: `twenty-sdk/define` is resolved at bundle time by the SDK define stub plugin, and since the unwrap already rewrote the call site, it bundles as dead code. Verified by building a component with `import { defineSettingsFrontComponent, createValidationResult } from 'twenty-sdk/define'` — output has a working render default export and no `twenty-sdk` imports. In practice the co-import can't occur anyway: runtime symbols live in `twenty-sdk/front-component`, a separate subpath, and type co-imports are elided by esbuild.

**Review by martmull — APPROVED** [review]
