### PR TITLE
Fix UI builds without Monaco

### LINKED ISSUE #26117: Front component build fails with Could not resolve "monaco-editor" when importing from twenty-ui/primitives/input
## Bug Description

A front component that imports a `Button` from `twenty-ui/primitives/input` does not build unless the app also installs `monaco-editor`:

```
$ yarn twenty dev:build
Building application files...
Build failed with 1 error:
node_modules/twenty-ui/dist/input-DOIOurw8.js:345:33: ERROR: Could not resolve "monaco-editor"
```

The component never renders `CodeEditor`. The failing import is `CodeEditor`'s lazy `import("monaco-editor")` from #23855. It sits in the chunk behind `twenty-ui/primitives/input`, and the `primitives/feedback` and `primitives/navigation` chunks import that chunk too. `monaco-editor` is a peer dependency. The twenty-ui README asks for it ("Install `monaco-editor` even if you never render a code editor", #26044), but the install step in [Using Twenty UI components](https://docs.twenty.com/developers/extend/apps/layout/front-components#using-twenty-ui-components) only adds `twenty-ui`, and the `create-twenty-app` template does not add it either.

**Repro.** Node 24.18, Yarn 4.13. A minimal app (application config and default role as in the `create-twenty-app` template) with `twenty-sdk`, `twenty-client-sdk` and `twenty-ui` at 2.41.0, `react` and `react-dom` 19, and no `monaco-editor`. Add:

```tsx
// src/front-components/button.tsx
import { defineFrontComponent } from 'twenty-sdk/define';
import { Button } from 'twenty-ui/primitives/input';

const ButtonOnly = () => <Button title="Hello" />;

export default defineFrontComponent({
  universalIdentifier: '0b7d3e61-5a2c-4f9e-8d14-7e6a1c3b2f45',
  name: 'Button only',
  component: ButtonOnly,
});
```

`yarn twenty dev:build` exits 1 with the error above.

It is the same on twenty-ui 1.0.0-alpha.2 (the version `create-twenty-app@2.40.0` pins) with twenty-sdk 2.31.0 and `import { Button } from 'twenty-ui/input'`: `dist/feedback-4pPehd1L.js:593:33: ERROR: Could not resolve "monaco-editor"`. 1.0.0-alpha.1 built, because its chunk only imported `@monaco-editor/react`.

## Expected behavior

A front component that uses a button, an input or a callout builds without installing a code editor it never renders. If `monaco-editor` has to stay a required peer, the front-component install step and the `create-twenty-app` template should include it.

## Technical inputs

- Only resolution needs the package. With `monaco-editor@0.56.0` installed (98 MB in `node_modules`) the component above builds to 754,865 bytes. With an empty package named `monaco-editor` (`export {}`) in its place, the output is byte-identical. The same holds on alpha.2 with twenty-sdk 2.31.0 (968,136 bytes both ways). The unused `CodeEditor` code is dropped, but its import still has to resolve.
- For that reason, marking the peer optional in `peerDependenciesMeta` would not fix the build on its own.
- Possible fix: give `CodeEditor` its own entry point (for example `twenty-ui/primitives/code-editor`), so the `input`, `feedback` and `navigation` chunks stop referencing `monaco-editor`.
- Workaround until then: a local workspace package named `monaco-editor` that only exports `{}`, pinned through `resolutions` in the root `package.json`.

### PR DESCRIPTION
**Pull request by bosiraphael**
Move the code editor and its header to `twenty-ui/components/code-editor` so other UI entry points build without Monaco.
`@monaco-editor/react` and `monaco-editor` become optional peer dependencies, and `CoreEditorHeader` is renamed to `CodeEditorHeader`.
Existing editor consumers must use the new entry point and install both Monaco packages.
A package check in CI keeps optional peer dependencies out of the root entry point, including its type declarations.
Also adds Storybook stories and a documentation page for the code editor and its header.

Fixes #26117

<a href="https://cubic.dev/pr/twentyhq/twenty/pull/26134?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

### CODE REVIEW

**Review by Weiko — APPROVED** [review]

**Review by martmull — APPROVED** [review]

File: packages/twenty-ui/scripts/checkOptionalDependencies.ts [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+      BARE_IMPORT_PATH_PATTERN.test(importPath)
+        ? [{ declarationFilePath, importPath }]
+        : collectBareDeclarationImports(
+            resolveDeclarationFilePath(declarationFilePath, importPath),
+            visitedDeclarationFilePaths,
+          ),
+  );
+};
+
+for (const entryPath of [ROOT_ENTRY_POINT.import, ROOT_ENTRY_POINT.require]) {
```
Comment (thomtrp) [inline packages/twenty-ui/scripts/checkOptionalDependencies.ts:89]: Non-blocking: the guard only covers the `.` entry point.

`src/index.ts` re-exports `components`, `icon`, `primitives`, `theme`, `theme-constants` and `utilities`, so a Monaco leak into any of those does show up in `dist/index.mjs`. But `assets`, `styles` and `testing` are not reachable from the root barrel, so a future optional-peer import there would pass silently. Generalizing the loop to every `exports` key except `./components/code-editor` looks close to free and would match what the README and docs now promise.

For what it's worth I checked that both halves of the check actually do their job, since a silently no-op guard would be the worst outcome here:
- esbuild `onResolve` plugins do fire under `packages: 'external'`, including for `import('monaco-editor')` (the dynamic form `CodeEditor.tsx` uses).
- `ts.preProcessFile` catches `import type`, `import { type x }`, inline `import("monaco-editor").editor.X` in type position, and `/// <reference types="monaco-editor" />`.

One brittleness note on the declaration walk: `resolveDeclarationFilePath` only tries `X.d.ts` and `X/index.d.ts` and throws otherwise. That works because vite-plugin-dts emits extensionless relative specifiers today; if that ever changes to `./foo.js` the check hard-fails with "Cannot resolve" instead of passing. It fails loudly, so low priority.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: packages/twenty-ui/src/components/code-editor/index.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+ *  | |  \ V  V /  __/ | | | |_| |_| | Any edits to this will be overridden
+ *  |_|   \_/\_/ \___|_| |_|\__|\__, |
+ *                              |___/
+ */
+
+export { CodeEditor } from './CodeEditor/CodeEditor';
+export { BASE_CODE_EDITOR_THEME_ID } from './CodeEditor/constants/BaseCodeEditorThemeId';
+export type { CodeEditorProps } from './CodeEditor/types/CodeEditorProps';
+export { getBaseCodeEditorTheme } from './CodeEditor/utils/getBaseCodeEditorTheme';
+export { CodeEditorHeader } from './CodeEditorHeader/CodeEditorHeader';
```
Comment (thomtrp) [inline packages/twenty-ui/src/components/code-editor/index.ts:14]: `CodeEditorHeader` needs no Monaco, but it is now only reachable through the Monaco entry point. A consumer that wants just the header has to install `@monaco-editor/react` for the bundler to resolve this barrel, since `CodeEditor.tsx` imports it statically.

This already shows up in the repo: `twenty-ui-input-gallery.front-component.tsx` now imports `twenty-ui/components/code-editor` purely to render `<CodeEditorHeader title="Editor" />`, and that entry point is the one the sibling gallery documents as unable to work in the front-component sandbox.

Grouping it with the editor is defensible on naming and cohesion grounds, so this is a judgment call rather than a defect. Splitting the header back out (or re-exporting it from `twenty-ui/components`) would keep the Monaco-free promise a bit tighter.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: packages/twenty-docs/developers/extend/apps/layout/front-components.mdx [hunk 3]
```diff
@@ -706,7 +706,7 @@ Twenty ships its component library as the [`twenty-ui`](https://www.npmjs.com/pa
 `twenty-ui` is published alongside the SDK packages with the same version. Add it to your app, pinned to the version of `twenty-sdk` and `twenty-client-sdk` you use:
 
 ```bash
-yarn add -D twenty-ui@2.40.0
+yarn add -D twenty-ui@2.42.0
```
Comment (thomtrp) [inline packages/twenty-docs/developers/extend/apps/layout/front-components.mdx:709]: 2.42.0 is not published yet: `packages/twenty-ui/package.json` is at 2.42.0 but the latest tag is `twenty/v2.41.0`. Since docs deploy from main, this command 404s for anyone following the guide between merge and the 2.42.0 release.

The line was previously 2.40.0 while 2.41.0 was already out, so the convention looked like "lag, then bump on release". Should this be 2.41.0, or is 2.42.0 close enough to shipping that it does not matter?

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by thomtrp — APPROVED** [review]
LGTM.

The entry-point split is consistent end to end: barrel generation, package exports, typesVersions, both vite configs, size-limit, docs, and every consumer. All 17 `CodeEditor` / `CodeEditorHeader` import sites are migrated and no `CoreEditorHeader` references remain.

I verified the new CI guard rather than taking it on faith, since a no-op guard would be the worst outcome here. Both halves work: esbuild's `onResolve` plugin fires under `packages: 'external'` (including for dynamic imports), and `ts.preProcessFile` catches every realistic `.d.ts` form of a Monaco reference. Details in the inline comment.

Three non-blocking notes inline, none of which need to hold up the merge. One extra observation: the `yarn.lock` hunk adding `twenty-ui: "workspace:*"` to `create-twenty-app` is unrelated drift left over from #26133 (main's package.json had it, the lockfile did not). Correct to include, just not obviously part of this change.

---
_Generated by [Claude Code](https://claude.ai/code)_
